### ISSUE TITLE
x/burn does not work as expected

### ISSUE THREAD

**Issue by discoverdefiteam** [terpnetwork/terp-core#155]
#### Specifications

Terp-Core version: `v4.0.0`
OS & Version: Windows/Linux/OSX
Commit hash:  `main`

#### Expected behavior
Send tokens to `x/burn`

#### Actual behavior
Unauthorized

#### Steps to reproduce the behavior
- Send tokens to burn module addr `terp1v7uw4xhrcv0vk7qp8jf9lu3hm5d8uu5yg038yh`

#### Backtrace

````
 ERR failure when running app err="rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: terp1v7uw4xhrcv0vk7qp8jf9lu3hm5d8uu5yg038yh is not allowed to receive funds: unauthorized [cosmos/cosmos-sdk@v0.47.5/x/bank/keeper/msg_server.go:44] With gas wanted: '18446744073709551615' and gas used: '30602' : unknown request"
````

When submitting logs: please submit them as text and not screenshots.

**Comment by hard-nett** [comment]
verified here: #160
